export const investmentOptions = [
  {
    name: 'Equity Mutual Funds',
    category: 'High Risk',
    expectedReturns: '12-15% p.a.',
    minimumInvestment: 'Rs. 500',
    description: 'A strong long-term option for compounding wealth through diversified equity exposure.',
    highlights: ['SIP friendly', 'Great for long-term goals', 'Higher short-term volatility'],
  },
  {
    name: 'Public Provident Fund',
    category: 'Low Risk',
    expectedReturns: '7.1% p.a.',
    minimumInvestment: 'Rs. 500',
    description: 'Government-backed savings with predictable returns and tax benefits.',
    highlights: ['Tax saving', '15-year horizon', 'Capital safety focused'],
  },
  {
    name: 'Fixed Deposits',
    category: 'Low Risk',
    expectedReturns: '6-7% p.a.',
    minimumInvestment: 'Rs. 1,000',
    description: 'Useful when stability matters more than aggressive growth.',
    highlights: ['Low volatility', 'Easy to understand', 'Best for short to medium term'],
  },
  {
    name: 'National Pension System',
    category: 'Medium Risk',
    expectedReturns: '9-12% p.a.',
    minimumInvestment: 'Rs. 500',
    description: 'A retirement-focused product combining equity and debt exposure.',
    highlights: ['Retirement focused', 'Tax benefits', 'Long-term discipline'],
  },
  {
    name: 'Gold ETF',
    category: 'Medium Risk',
    expectedReturns: '8-10% p.a.',
    minimumInvestment: 'Rs. 1,000',
    description: 'A simple way to add gold diversification without handling physical gold.',
    highlights: ['Inflation hedge', 'Exchange traded', 'Diversification support'],
  },
  {
    name: 'Debt Mutual Funds',
    category: 'Low Risk',
    expectedReturns: '6-8% p.a.',
    minimumInvestment: 'Rs. 500',
    description: 'Suitable when you want steadier income with lower volatility than equities.',
    highlights: ['Lower volatility', 'Income-oriented', 'Useful for balance'],
  },
];
